spring.application.name=ecommerce


server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/fullstack_eticaret
spring.datasource.username=postgres
spring.datasource.password=Turantos.62

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html

iyzico.api-key=sandbox-2R2ezFnZZL3atjzOIMck2Gknh0145Yp0
iyzico.secret-key=sandbox-ku48hNKfsSKEhivrRwE3Cji4kXA5QYPU
iyzico.base-url=https://sandbox-api.iyzipay.com