spring.application.name=ecommerce


server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/fullstack_eticaret
spring.datasource.username=postgres
spring.datasource.password=Turantos.62

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html